name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  COVECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      
    - name: Poetry export requirements.txt
      run: ~/.poetry/bin/poetry export -f requirements.txt > requirements.txt
      
    - name: Install dependency
      run: ~/.poetry/bin/poetry install
      
    - shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
        AWS_PROFILE: netflex-secrets-manager  
        run: ehco"$AWS_PROFILE""
    
    - name: run test
      run: ~/.poetry/bin/poetry run pytest --cov app
            
    - name: codecov
      run: ~/.poetry/bin/poetry run codecov

